### ISSUE TITLE
Session data lost on page refresh

### ISSUE THREAD

**Issue by Alexander-Krause-Glau** [ExplorViz/explorviz-ui-frontend#100]
We show the current username in the top right corner. The name is not shown on page refresh (F5 or Ctrl + R), probably due to lost session data.

This requires a fix.

We use `ember-simple-auth` for authentication in Ember. [Issue 523](https://github.com/simplabs/ember-simple-auth/issues?utf8=%E2%9C%93&q=is%3Aissue+523) might give a hint. However, I think the problem may also origin in our session handling.

**Comment by malte-hansen** [comment]
Fixed with b4d6710917c8362e2ed84b5c17216545136af983
