### ISSUE TITLE
TagNames for Ember components

### ISSUE THREAD

**Issue by Alexander-Krause-Glau** [ExplorViz/explorviz-ui-frontend#102]
Ember automatically generates `div` elements for components, if no `tagName` is applied. This makes traversing the DOM tree pretty cumbersome. 

## Refactoring (Attention: See comment below)
We should always modify the [`tagName` and `classNames`](https://guides.emberjs.com/release/components/customizing-a-components-element/) property for components if possible, e.g., [footer component](https://github.com/ExplorViz/explorviz-frontend/blob/dev-1/app/components/page-setup/footer.js) with related [template](https://github.com/ExplorViz/explorviz-frontend/blob/dev-1/app/templates/components/page-setup/footer.hbs). This prevents Ember from generating `div` elements.

## Research, then Refactoring
However, sometimes you cannot change the `tagName` because our component is simply a wrapper, e.g., for an addon's provided component, see [navbar.js](https://github.com/ExplorViz/explorviz-frontend/blob/dev-1/app/templates/components/page-setup/navbar.hbs). We could set the [`tagName` to `' '`](https://stackoverflow.com/questions/36134964/how-do-you-remove-the-tagname-in-a-component-in-ember-2-4), but in the past this was supposedly *bad practice*. I cannot find any good evidence (except the Stackoverflow comment) that proves the *bad practice* with facts. 

Todo:
- Refactor anything that works for the first part
- Research the second part and comment here

**Comment by Alexander-Krause-Glau** [comment]
If `tagName: ''` is used with jQuery, e.g., `this.$()`, an error will occur on the JS console:

`
Error: Assertion Failed: You cannot access this.$() on a component with tagName: "" specified.
`

I could not find any other drawback. Since we can simply set HTML ids for HTML entities in related template files, we can always "workaround" this issue by using `$('#id')`, where `id` is the HTML identifier.

Therefore, I reckon we can safely remove the tagName. I further propose to remove all tagNames (do not apply the first approach above) to be consistent.

**Comment by Alexander-Krause-Glau** [comment]
Removed tagNames via b27a5712cb4c72b111a6793613e0d82a87600960. 

TODO:
- Check if there are remaining Ember-generated `div` elements and remove them
- Finally, close this issue

**Comment by dan0x09** [comment]
All components seem to use empty tagName by now, so I'm closing this.
