### ISSUE TITLE
Service-based event bus

### ISSUE THREAD

**Issue by Alexander-Krause-Glau** [ExplorViz/explorviz-ui-frontend#115]
We need an event bus, so that extensions and core components can recognize, if an event occured, e.g., user clicked entity, entity was highlighted etc.

Are there better options than using an Ember service?

**Comment by malte-hansen** [comment]
According to my knowledge, an event bus can be implemented best by combining an Ember service with the Ember Evented mixin. 

Source: https://emberigniter.com/communication-between-distant-components/

**Comment by Alexander-Krause-Glau** [comment]
Dunno about the [state of mixins](https://www.reddit.com/r/emberjs/comments/bcezys/embermixin_in_the_world_of_octane_native_classes/) in the upcoming Ember Octane release.

I have some ideas and will discuss them with you and @dan0x09 in one of our upcoming meetings.
