### ISSUE TITLE
Refactor URL builder

### ISSUE THREAD

**Issue by Alexander-Krause-Glau** [ExplorViz/explorviz-ui-frontend#116]
Some functionality is implemented. Validate and refactor.

**Comment by malte-hansen** [comment]
The original URL builder code was not functional anymore and thus removed.
A successor of the URL builder could implement a snapshot feature such that the current state is copied as JSON into the [clipboard ](https://www.npmjs.com/package/ember-cli-clipboard). 
Later on this clipboard entry should be validated and then used to recover the previously copied state.

**Comment by Alexander-Krause-Glau** [comment]
Continue after refactoring of rendering
