### ISSUE TITLE
Enhance user management dialog with user settings

### ISSUE THREAD

**Issue by Alexander-Krause-Glau** [ExplorViz/explorviz-ui-frontend#119]
On init, the user management fetches the default `usersetting` object (always id: 1). This object can contain boolean, String, and numerical values. 

Use this `usersetting` object to show a settings dialog for user creation. The object itself is NOT referenced, but its keys and values are embedded in the settings JSON object of a user record (to see what I mean: after login check Ember inspector -> Data  tab). 

The settings dialog should be a separated component, such that we can use the same component in general settings for the current session user.

- Use `ember-toggle` for boolean values.
- Use inputs for numerical and String-based values

**Comment by Alexander-Krause-Glau** [comment]
I use this issue to propose a new draft for the user settings. I like the current implementation, but already see a big disadvantage in the code quality due to all those single attributes in the `UserSettings` class.

We should use (three) different Maps with String-based keys and different types of values, i.e., String, numeric, and boolean.

Disadvantage: We need to initialize these Maps with the settings, always check for existence of a key, and read its value. But I think these are no drawback, since we might provide so many settings that the whole class is cluttered and some PMD rules would eventually trigger, e.g., [TooManyFields](https://pmd.github.io/latest/pmd_rules_apex_design.html#toomanyfields).

**Comment by dan0x09** [comment]
All done with [`9352a68`](https://github.com/ExplorViz/explorviz-backend/commit/9352a68996413d7e97ba771eea69374a3c5004c7) (backend) and [`39b1a29`](https://github.com/ExplorViz/explorviz-frontend/commit/39b1a29bbd68c45ce9dd65f56db0f0f26e3c4ad0) (frontend).
