### ISSUE TITLE
Partly hidden application names

### ISSUE THREAD

**Issue by malte-hansen** [ExplorViz/explorviz-ui-frontend#128]
![explorviz_bug_applicationname](https://user-images.githubusercontent.com/38311128/51803203-8117e400-2252-11e9-89e2-cfb103df990e.png)

Using the sample application of Kieker it occured that the name of the application (on the foundation) was partly covered by components (see picture). It should be investigated whether the components or the label for the application name should be positioned differently during layouting of the application.

**Comment by Alexander-Krause-Glau** [comment]
Already open (?), see https://github.com/ExplorViz/explorviz-frontend/issues/29

**Comment by malte-hansen** [comment]
This issue, further specifying #29, added as a comment to #29 by @Alexander-Krause and thus closed due to duplicate issue
