### ISSUE TITLE
Split user management into multiple components

### ISSUE THREAD

**Issue by dan0x09** [ExplorViz/explorviz-ui-frontend#130]
Working on the `user-management` and taking a look at it lately made me realize that the component has gotten quite large with its almost 300 LOC and an additional ~200 lines in its corresponding template. Since it likely will grow in the future, the code maintainability and clarity might suffer.

The component already sort of divides into 3 "sub-pages", i.e. the page with the user list, the user-creation page and user-edit page. Currently, we decide what is rendered using the `page` property and if-else statements in the template. To improve code quality, I suggest actually splitting the `user-management` into the 3 components `user-list`, `user-edit` and `user-creation`.

Furthermore, we can use the advantage of `routes` to get rid of the `page` property (e.g. `/configuration/usermanagement/edit/:user_id` to display the `user-edit` component for the user with the given id).

**Comment by Alexander-Krause-Glau** [comment]
Sounds good. I think we do not use sub routes at this point, but this looks like a good fit to test this.

**Comment by dan0x09** [comment]
Done with [`994953c`](https://github.com/ExplorViz/explorviz-frontend/commit/994953c3633fb2122c81e3bc6930a8f234c93d24).
The former `user-management` component was split into

- `user-list` with route `/configuration/usermanagement/users`
- `user-creation` with route `/configuration/usermanagement/new`
- `user-edit` with route `/configuration/usermanagement/edit/:user_id`
