### ISSUE TITLE
Loading a landscape via timeline should notify user upon completion 

### ISSUE THREAD

**Issue by Alexander-Krause-Glau** [ExplorViz/explorviz-ui-frontend#134]
Some landscapes are pretty similar due to persistent load etc. Therefore, it is not really clear when the landscape visualization was really updated at the moment.

We should implement this, since loading, updating Ember store, and re-render might take some time.

**Comment by czirkelbach** [comment]
Chart.js features several events like when the rendering is inprogress and when it is completed.

**Comment by Alexander-Krause-Glau** [comment]
Nice feature, but not what I meant.

I used the AlertifyHandler (a77def6) to notify the user about the updated visualization. 

**TODO**: I am not happy with this implementation, since it is really hardcoded and can be easily forgotten when implementing a new visualization. We must realize a fancy dynamic approach for this problem.

Nevertheless, the current realization showed some immense problems (see Issue #135, #136).
