### ISSUE TITLE
Enhance tables in sidebar and user-management

### ISSUE THREAD

**Issue by dan0x09** [ExplorViz/explorviz-ui-frontend#141]
For now, we've been using simple tables for displaying data in both the `sidebar` (trace-selection) and the `user-list` as part of the `user-management`. While the data itself is displayed fine, the tables lack some features such as sorting by attribute, searching, or pagination (since tables might get rather long), just to name a few.

I think we should enhance our tables with such features for improved usability and workflow.

I've stumbled across [`Bootstrap Table`](https://bootstrap-table.com/), which includes all the features mentioned above (and more) and seems to be a good fit. If there's other, even better, suggestions, please post them.

**Comment by malte-hansen** [comment]
Indeed,  [`Bootstrap Table`](https://bootstrap-table.com/) would add many functionalities which would be of great use for us. However, it seems like Bootstrap Table only supports static HTML tables and JSON as data input. Using Bootstrap Table with Handlebars, i.e. dynamic tables leads to errors when the content of a table changes. 
If this issue cannot be resolved, the only options would be to adapt the way data is accessed for table generation or do not use Bootstrap Table for tables in the sidebar at all.

**Comment by dan0x09** [comment]
Regarding pagination also see #186 
For both attribute sorting and searching we need the backend to support it. Afaik the backend already supports filtering for roles and batch ids, but not yet for username prefixes.
Regarding Bootstrap Table: As @Malte-Hansen rightfully mentioned, it's not as good a match as initially thought, so we we'll drop that idea and should implement sorting and seraching ourselves.

**Comment by Alexander-Krause-Glau** [comment]
I close this issue in favor of https://github.com/ExplorViz/explorviz-backend/issues/109
