### ISSUE TITLE
Import / Export of landscape files

### ISSUE THREAD

**Issue by Alexander-Krause-Glau** [ExplorViz/explorviz-ui-frontend#161]
ExplorViz requires an import / export functionality for landscapes. 

- Administrators should be able to upload files (with a custom `.expl` ending) which contain JSON-API representations of landscapes
- `frontend` should upload (maybe pre-validate) to `history-service`
- `history-service` should (validate landscape by parsing to Java and) persist landscape

Things to check:

- Id handling (update IDs on upload or not necessary since UUID?)

**Comment by czirkelbach** [comment]
Implemented in dev-1.
