### ISSUE TITLE
Refactoring of landscape selection dialog in replay

### ISSUE THREAD

**Issue by Alexander-Krause-Glau** [ExplorViz/explorviz-ui-frontend#165]
We require a new view / dialog that uses the data described in https://github.com/ExplorViz/explorviz-backend/issues/78, so that users can choose a landscape that they want to inspect.

**Comment by czirkelbach** [comment]
Currently under development in combination with new timeline.

**Comment by Alexander-Krause-Glau** [comment]
Current implementation works, but should be refactored with a suitable dialog for landscape selection based on https://github.com/ExplorViz/explorviz-backend/issues/78. The timeline is not a good fit imho. I rename this issue to keep track of this work.
