### ISSUE TITLE
A library for backend mocking (remove)

### ISSUE THREAD

**Issue by dan0x09** [ExplorViz/explorviz-ui-frontend#179]
A while back, @Alexander-Krause introduced a mocked environment using basic `express` routing. It's turned out to be very useful during development, since it's no longer required to have the actual backend services running and has also exposed bugs in the backend implementation due to inconsistencies in the backend and mocked implementation of certain endpoints.

There have been some drawbacks however, which made implementing these mocked endpoints rather difficult, e.g., storing data s.a. user records. This especially became clear when implementing the mocked endpoints for the user service. Processing JSON API data and especially responding with a JSON API serialized response is rather difficult and becomes an extra effort for the developer.

Fortunately, there is a good `mock library` for Ember called [EmberCLI Mirage](https://www.ember-cli-mirage.com/), which we could use. It makes defining endpoints easy and comes with a `database` to store and query records from. It automatically detects the existing models used by ember-data and let's you create records for a certain model and insert it into the database. Mirage supports JSON API and de-/serializes data itself. To create some initial data, it allows defining factories, which can be used to create a list of records. What's also a nice feature is that Mirage can be used in tests. So one could easily create a couple users and test whether they are rendered correctly in the user list.

After spending a some hours using the library, it seems very easy to use and a good fit for ExplorViz.

**Comment by czirkelbach** [comment]
In this context we should update the mocking (data) to be consistent with the current version of the backend API, especially to allow mocking the added replay functionality.

**Comment by Alexander-Krause-Glau** [comment]
@dan0x09 will check if there is an alternative to SSE, since they do not work well with Mirage. Additionally, we use a polyfill in the frontend code at the time of writing, due to the fact that the SSE implementation does not allow HTTP headers to be included.

**Comment by Alexander-Krause-Glau** [comment]
We will remove the backend mocking in the frontend and employ a docker-compose file to startup the ExplorViz backend stack and a sample application.

**Comment by Alexander-Krause-Glau** [comment]
Merged.
