### ISSUE TITLE
Provide DummyMode for Development

### ISSUE THREAD

**Issue by czirkelbach** [ExplorViz/explorviz-ui-frontend#23]
Idea: Provide a Dummy- /Offline Mode, thus no running backend is needed for development

**Comment by czirkelbach** [comment]
Could be implemented using the configuration.json file.

**Comment by Alexander-Krause-Glau** [comment]
Possible implementation details:

1. Bypass ember-simple-auth for authentication
2. Create a file called `dummy-landscape.json` and insert the parsed dummy landscape string from the backend (use Google Chrome network tab to copy this string).
3. On startup check a flag (here lies the same problem as shown in issue #22)
4. If we want to develop offline, use something like [this](https://emberjs.com/api/ember/2.18/classes/Promise) to read the file as *string*, not json
5. Use landscape serializer (?) to deserialize the object, [pushPayload](https://github.com/emberjs/data/blob/v2.16.0/addon/serializers/json-api.js#L242) might work

**Comment by Alexander-Krause-Glau** [comment]
Already implemented.
