### ISSUE TITLE
Performance Enhancement for Ember Store

### ISSUE THREAD

**Issue by czirkelbach** [ExplorViz/explorviz-ui-frontend#26]
During runtime the Ember Store is growing and consumes more and more memory.
Idea: Cleanup the store and keep only important data, possibly can be triggered via JS?

**Comment by czirkelbach** [comment]
Can we now safely remove old data?

**Comment by Alexander-Krause-Glau** [comment]
Todo: Try to use the `unloadRecord` function of an Ember model and report back if it works.  Use this in landscape-listener.

**Comment by Alexander-Krause-Glau** [comment]
https://github.com/emberjs/data/issues/

closed issue number: 1849
