### ISSUE TITLE
Build Role-based Authorization

### ISSUE THREAD

**Issue by czirkelbach** [ExplorViz/explorviz-ui-frontend#27]
Specific routes should not be accessible for every user.
Related to the corresponding [backend issue](https://github.com/ExplorViz/explorviz-backend/issues/5).

**Comment by Alexander-Krause-Glau** [comment]
Done.

**Comment by Alexander-Krause-Glau** [comment]
Reopening: Backend has this functionality, but frontend route authorization is missing.

This addon might be helpful: https://github.com/envoy/ember-route-constraints

**Comment by dan0x09** [comment]
Among other things, route constraints were added with [`994953c`](https://github.com/ExplorViz/explorviz-frontend/commit/994953c3633fb2122c81e3bc6930a8f234c93d24). We're now using the `ember-route-contraints` addon as suggested by @Alexander-Krause 
I added one constraint limiting the `/configuration/usermanagement` route and its subroutes to admin users only and this is working well.
For further reference on how to add route constraints, see 

> https://github.com/envoy/ember-route-constraints

**Comment by Alexander-Krause-Glau** [comment]
Nice work.
