### ISSUE TITLE
[Extension] ColorPicker extension - visually impaired mode

### ISSUE THREAD

**Issue by czirkelbach** [ExplorViz/explorviz-ui-frontend#33]
Provide a visually impaired mode via the [colorpicker extension](https://github.com/ExplorViz/explorviz-frontend-extension-colorpicker)

**Comment by Alexander-Krause-Glau** [comment]
@czirkelbach Done?

**Comment by czirkelbach** [comment]
@Alexander-Krause Still some refactoring and testing needs to done.

**Comment by Alexander-Krause-Glau** [comment]
Done.
