### ISSUE TITLE
Implement a stable version of the new timeline

### ISSUE THREAD

**Issue by czirkelbach** [ExplorViz/explorviz-ui-frontend#34]
Implement a stable version of the new timeline, which also provides the ability to load a specific landscape (as described [here](https://github.com/ExplorViz/explorviz-frontend/issues/24))
Should be later improved via panning, zooming and performance-optimization.

**Comment by czirkelbach** [comment]
[BUG] Timestamps are sometimes missing, when exchange with backend is paused.

**Comment by Alexander-Krause-Glau** [comment]
Let's discuss: Which high performant library can we use?

**Comment by Alexander-Krause-Glau** [comment]
New idea: Timeline is always visible via small bar at the bottom of the page. Clicking the bar will slide up the timeline.

**Comment by Alexander-Krause-Glau** [comment]
While we are working on this: We should also consider to rename the `time-shift` and `timeshift` aspects to `timeline`. What do you think @czirkelbach ?

**Comment by czirkelbach** [comment]
Good idea, I rename it in the next days.

**Comment by czirkelbach** [comment]
For release version 1.3.0 we implement a basic version, which shows the last timestamps but does no allow to load one.

**Comment by Alexander-Krause-Glau** [comment]
With pan and zoom?

**Comment by czirkelbach** [comment]
> 
> 
> With pan and zoom?

No, thats coming in the next release.

**Comment by Alexander-Krause-Glau** [comment]
Let's test the performance of pan and zoom by manually inserting 8640 points before we choose the wrong lib (again).

**Comment by czirkelbach** [comment]
Implemented with #180.
