### ISSUE TITLE
[Extension] Provide a teleporation mode for the vr extension

### ISSUE THREAD

**Issue by czirkelbach** [ExplorViz/explorviz-ui-frontend#35]
Additionally provide a quick-start guide with controller-mapping images (Vive & Rift) for the upcoming release.

**Comment by czirkelbach** [comment]
Good examples for a controller layout are:

https://www.gravitysketch.com/wp-content/uploads/2017/07/gravity_sketch-vr-htc_vive_controller_configuration.jpg

https://www.gravitysketch.com/wp-content/uploads/2017/07/gravity_sketch-vr_oculus_touch_configuration.jpg

https://help.revizto.com/user_manual/vr_mode.html

**Comment by Alexander-Krause-Glau** [comment]
Done.
