### ISSUE TITLE
Don't use double click anymore

### ISSUE THREAD

**Issue by Alexander-Krause-Glau** [ExplorViz/explorviz-ui-frontend#38]
The double click is an old pc-era based feature. It will (probably) never find its way into mobile devices.

We should discuss, if we want to use 

1. The Tap gesture for opening / closing packages
2. The Press gesture for highlighting entities

Have a look at this demo: https://codepen.io/jtangelder/pen/lgELw Again: A short mouse click would open / close packages (double click at the moment). Holding the mouse button for a short time would highlight entities.

What do you say?

**Comment by czirkelbach** [comment]
We should implement this enhancement for the upcoming release.

**Comment by Alexander-Krause-Glau** [comment]
@thacau VR mode (mouse interaction) might be damaged due to the changes in [HammerInteraction](https://github.com/ExplorViz/explorviz-frontend/commit/15ee3b8d3b67cdb03ec4c37bfe0cb72d950c8210#diff-45bd0d3d89d2cf436b2893847f2ae73e)

**Comment by Alexander-Krause-Glau** [comment]
Commit 71a4d90 reverts implementation, since doubletap / double click works on mobile devices
