### ISSUE TITLE
Reset Route by clicking on Navbar Item

### ISSUE THREAD

**Issue by czirkelbach** [ExplorViz/explorviz-ui-frontend#39]
By clicking on a navbar item, the respective route should trigger a reset action / function.
The action needs to be defined for each route, especially for extensions.

Idea: Implement a parent route `BasicRoute`, which provides an action `reset` can be implemented in every route via extend.

**Comment by Alexander-Krause-Glau** [comment]
@thacau @czirkelbach Reason for implementation: This was urgent for my extension.

**Comment by czirkelbach** [comment]
Needs to be implemented in VR extension @thacau.

**Comment by Alexander-Krause-Glau** [comment]
Add information to "Developing Addons" Wiki.

**Comment by thacau** [comment]
done
