### ISSUE TITLE
Please Provide Credentials for the Live-Demo

### ISSUE THREAD

**Issue by SoerenHenning** [ExplorViz/explorviz-ui-frontend#44]
The new Live-Demo seems to be available at http://samoa.informatik.uni-kiel.de:8181/explorviz-frontend

However without knowing username and passwort, it's not possible to login.

**Comment by Alexander-Krause-Glau** [comment]
Username: admin, password: admin.

Thank you. Will be added to README.md

**Comment by SoerenHenning** [comment]
I think it would be better to have them on the [login page](http://samoa.informatik.uni-kiel.de:8181/explorviz-frontend/login) (only for the Live-Demo) since most users that click on the "Live-Demo" button on your website won't look in the README before.

Or, even better, an automatic login of the default user as in the old Live-Demo.

**Comment by Alexander-Krause-Glau** [comment]
Yes you are right, I will update the default text of the HTML input elements.

**Comment by Alexander-Krause-Glau** [comment]
Changed in https://github.com/ExplorViz/explorviz-frontend/commit/57e6944a6140e2bd90867bfc64d894315c225b1a. Running live demo needs to be updated.

**Comment by Alexander-Krause-Glau** [comment]
Done.
