### ISSUE TITLE
Switch from TravisCI to Jenkins

### ISSUE THREAD

**Issue by Alexander-Krause-Glau** [ExplorViz/explorviz-ui-frontend#46]
I open this issue here, but it affects the explorviz-backend as well. I would like to switch to Jenkins for a full control CI build. For that, remote master branches should be protected. To contribute changes to the master, developers should create a pull request (as shown in https://github.com/kieker-monitoring/kieker/pulls) with changes, which can be auto-merged by git. Then @czirkelbach  or I use the [Jenkins Github pull request builder plugin](https://wiki.jenkins.io/display/JENKINS/GitHub+pull+request+builder+plugin) to trigger a build that does the following:

- [ ] [Most of these steps](https://www.oreilly.com/learning/configuring-a-continuous-delivery-pipeline-in-jenkins)
- [ ] [Test environment](https://www.logitblog.com/the-12-steps-of-continuous-integration/)

Static analysis should consist of the following:

*Backend*:
- [ ] Checkstyle
- [ ] Findbugs/Spotbugs
- [ ] PMD
- [ ] Sonarqube
- [ ] Code Climate

*Frontend*:
- [ ] ESLint
- [ ] Code Climate [Example](https://codeclimate.com/github/emberjs/ember.js/issues)

More sources:
- https://jenkins.io/blog/2017/04/18/continuousdelivery-devops-sonarqube/

**Comment by Alexander-Krause-Glau** [comment]
Maybe we can add an additional job that checks if dependencies have updates and reports the result.

- https://github.com/ben-manes/gradle-versions-plugin
- https://www.npmjs.com/package/npm-check-updates

**Comment by czirkelbach** [comment]
Decision towards TravisCI
