### ISSUE TITLE
Tutorial mode

### ISSUE THREAD

**Issue by Alexander-Krause-Glau** [ExplorViz/explorviz-ui-frontend#8]
Rebuild tutorial mode

**Comment by czirkelbach** [comment]
Feature not necessary anymore.

**Comment by czirkelbach** [comment]
Currently under development by @helge-mueller.

**Comment by czirkelbach** [comment]
Implemented in [tutorial extension](https://github.com/ExplorViz/explorviz-frontend-extension-tutorial).
