### ISSUE TITLE
Customizable user options for configuration route

### ISSUE THREAD

**Issue by Alexander-Krause-Glau** [ExplorViz/explorviz-ui-frontend#80]
This issue shall be used to collect and discuss customizable user options for the configuration route. These are open for implementation. For starters, see this first list:

- Toggle hover effect for landscape and application
- Toggle unhighlight behavior on selection, [if entity is already highlighted](https://github.com/ExplorViz/explorviz-frontend/blob/dev-1/app/utils/application-rendering/interaction.js#L247)
- Toggle hierarchircal / flat landscape visualization (closed / always open entities)
- Toggle transparency effect on selection for application visualization
- Customize transparency effect's intensity
- Communication arrow size

Toggleable options should use the [ember-toggle-addon](https://github.com/knownasilya/ember-toggle). We already use this addon in the discovery-detail-tables, e.g., [monitoring-information.hbs](https://github.com/ExplorViz/explorviz-frontend/blob/dev-1/app/templates/components/discovery/procezz-details-tables/monitoring-information.hbs#L13).

**Comment by Alexander-Krause-Glau** [comment]
We could save these options as key-value list inside the authentication service's DB, i.e., as property of a user.

**Comment by Alexander-Krause-Glau** [comment]
@lotzk: For testing; implement a Java class `UserSettings` that holds a key value list with one element `"app-viz-class-color": "0xFF0000"` and is referenced by the admin user.

**Comment by malte-hansen** [comment]
A suggestion for an additional configurable feature:

- toggle threePerformance windows

**Comment by lotzk** [comment]
This is now supported by the backend. You can add arbitrary settings (as strings) to a user, for example:
```
{
	"data": {
		"type": "user",
		"attributes": {
			"username": "name",
			"password": "pw",
			"settings": {
                 		"app-viz-class-color": "0xFF0000",
				"toogle-threePerformance-windows": "true"
      			}
		}
	}
}
```

**Comment by Alexander-Krause-Glau** [comment]
The admin user now contains an attribute for the frontend fps counter. This is also handled by the frontend, therefore no fps counter, yay.

@lotzk @dan0x09 I rethought the settings. Unfortunately, I now reckonthat we have to provide a JSON:API-based settings object, since we need to obtain all possible settings on user creation and possibly change a setting for a to-be-created user. Again, data exchange between frontend and backend must be based on JSON:API. 

We should provide a JSON:API endpoint for a setting resource. This resource contains all possible settings (Strings, booleans and numerical values). I will probably start with this tomorrow.

**Comment by dan0x09** [comment]
> * Toggle hover effect for landscape and application
> * Toggle unhighlight behavior on selection, [if entity is already highlighted](https://github.com/ExplorViz/explorviz-frontend/blob/dev-1/app/utils/application-rendering/interaction.js#L247)
> 
Implemented with [`313d502`](https://github.com/ExplorViz/explorviz-frontend/commit/313d5023514701eb199ffe5f70f3af679173a4d4)

> * Toggle transparency effect on selection for application visualization
> * Customize transparency effect's intensity
> * Communication arrow size
> 
Implemented with [`f454152`](https://github.com/ExplorViz/explorviz-frontend/commit/f45415249bba6ed7831a2a6455933560894b37d2)

> * toggle threePerformance windows
>
Working with [`f454152`](https://github.com/ExplorViz/explorviz-frontend/commit/f45415249bba6ed7831a2a6455933560894b37d2)

**Comment by Alexander-Krause-Glau** [comment]
Can be closed after usersettings branch in backend was merged and frontend uses the new description objects?

Todo: Implement a boolean that toggles, if a click on the visualization tag should reload the landscape visualization or the last seen visualization, e.g., application visualization.

**Comment by Alexander-Krause-Glau** [comment]
Implemented, therefore closing this issue. Settings for visualization stuff can be further implemented in the next release or during the rendering refactoring (planned for october - april)
