### ISSUE TITLE
Show SQL statements for single application

### ISSUE THREAD

**Issue by Alexander-Krause-Glau** [ExplorViz/explorviz-ui-frontend#83]
In application visualization: Show a panel with all executed SQL statements.

**Comment by czirkelbach** [comment]
ToDo for next release:
- [ ] `<undefined` statements occur in the frontend. Investigate the backend and or Kieker. 
- [x] sort and filter capabilites would be useful
- [x] idea: hide all non selected queries to gain more page space for the query details
