### ISSUE TITLE
User management dialog

### ISSUE THREAD

**Issue by Alexander-Krause-Glau** [ExplorViz/explorviz-ui-frontend#84]
Provide user management GUI forms with respect to https://github.com/ExplorViz/explorviz-backend/issues/27

**Comment by Alexander-Krause-Glau** [comment]
@dan0x09 Today, I tried to implement an endpoint for the authentication service that essentially returns a container with a list of all string-based roles (atm a role is simply a string). This endpoint should be used for the ember-power-select based role selection. 

I instantly disliked this implementation and deleted all this code when I reached the frontend. Due to the (mostly) RESTful design this container classes come really unhandy when using Ember-Data. Ideally, we should only need to call `this.get('store').findAll('role')` and  insert the obtained roles in the ember-power-select dialog.

Eventualy, this means that I will try to refactor the backend's roles for authorization (classes instead of strings)

**Comment by czirkelbach** [comment]
TODO

- list of all users
- remove single user
- edit user information (name, password, role)

**Comment by dan0x09** [comment]
Done with [`00c355e`](https://github.com/ExplorViz/explorviz-frontend/commit/00c355e228b662978d324ca7b6b03756c99beaf7), [`2760f06`](https://github.com/ExplorViz/explorviz-frontend/commit/2760f063120bb20c760883f5e64d01e611285df6), [`197acd2`](https://github.com/ExplorViz/explorviz-frontend/commit/197acd2cd90c2ccc482fc7a091b6c580855b57b4), [`8a43f28`](https://github.com/ExplorViz/explorviz-frontend/commit/8a43f28d51ea6c151b5f53ad24c10c6942b26bd0), [`022a055`](https://github.com/ExplorViz/explorviz-frontend/commit/022a0553ffddc4da3f596ea86a12851817c547b9), [`09ae116`](https://github.com/ExplorViz/explorviz-frontend/commit/09ae11665e4e4d1d623133c7cff624c4815c6edc), [`ac19c65`](https://github.com/ExplorViz/explorviz-frontend/commit/ac19c657df9bc28579ede50a15d40ed39b11f3dd) (last).
