### ISSUE TITLE
Trace highlighting

### ISSUE THREAD

**Issue by Alexander-Krause-Glau** [ExplorViz/explorviz-ui-frontend#85]
In application visualization: Provide a mechanic to highlight single traces. Grey-out non-trace-related elements similar to entity highlighting.

See: https://github.com/ExplorViz/explorviz-backend/blob/dev-1/landscape/src/main/java/net/explorviz/landscape/model/application/RuntimeInformation.java

**Comment by czirkelbach** [comment]
Additionally, a panel with all traces behind a selected communication line should be shown.

**Comment by Alexander-Krause-Glau** [comment]
The backend creates new instances for communication-related aspects, since the communication itself is essentially a new one, e.g., between class A and B. We must refactor the backend, such that instances are reused, i.e., only updated.

**Comment by czirkelbach** [comment]
Improvements for next release 1.3.1:
- [x] template (high priority): duration (ms): Values are formatted with `.` or `,`. Needs to be fixed
- [x] template: time unit changeable via click on table header -> e.g. ms to s
- [x] template: sort and filter capabilites would be useful
- [x] template: hide all non selected traces to gain more page space for the trace step details
- [x] template / visualization: clazzes should be clickable in table and be centered by camera to locate them
- [x] visualization: show only current tracestep communication direction (arrow), even when communication exists between two clazzes
- [x] visualization: center (and zoom?) on selected tracestep - makes it easier to follow the trace

**Comment by malte-hansen** [comment]
The main issues. proposed by the original thread author, are solved.
The features, which still have room for improvement, mainly are concerned with the trace replayer.
These features will be covered by another issue ( #152 ).
