### ISSUE TITLE
Use navbar in Discovery GUIs instead of accordion

### ISSUE THREAD

**Issue by Alexander-Krause-Glau** [ExplorViz/explorviz-ui-frontend#88]
Discovery mode uses Bootstrap Accordion for different dialogs. IMO, accordions are exhausting to use due to scrolling etc. 

We should employ a navbar as shown [here (second navbar in this section)](https://getbootstrap.com/docs/4.0/components/navs/#javascript-behavior).

**Comment by Alexander-Krause-Glau** [comment]
Implemented with 74a154cba1d1957fd17e527d9336d2574ac69524.

Remaining problems:

- Scrollable container is chopped (see `procezz-details/execution-information`)
- Changing the name of an agent in `Agent-Details/General-Information` shows an error (something like `You modified "navItems" twice on <explorviz-frontend@component:bs-tab::ember373> in a single render.`. This error is linked with an issue, but I do not know how to fix it atm.

**Comment by dan0x09** [comment]
Closed with [`ab04b39`](https://github.com/ExplorViz/explorviz-frontend/commit/ab04b39424182e9cbc81e18d900cc0cdc474606f), [`ecb6f64`](https://github.com/ExplorViz/explorviz-frontend/commit/ecb6f645bbbce137b6ecfda94a99f157053f6962), [`2ecd9b8`](https://github.com/ExplorViz/explorviz-frontend/commit/2ecd9b85b85af56a7b7a4d7d5382112f6aa0c9ad), [`1bb9b3c`](https://github.com/ExplorViz/explorviz-frontend/commit/1bb9b3ca6601a159a51866a7f7b5981c6f6ca928).
