### ISSUE TITLE
Refactor navbar with ember-bootstrap

### ISSUE THREAD

**Issue by Alexander-Krause-Glau** [ExplorViz/explorviz-ui-frontend#93]
Refactor all navbars, since we use the [ember-bootstrap addon](https://www.ember-bootstrap.com/#/components/navbars).

**Comment by dan0x09** [comment]
Closed with [d145bf8](https://github.com/ExplorViz/explorviz-frontend/commit/d145bf80f9fbbd475947c5ec08ba49409b649abc).
